CREATE TABLE image(
--		id INT generated by default as identity (start with 1) not null,
		image_uri VARCHAR(2000) NOT NULL,
		page_uri VARCHAR(2000) NOT NULL,
		date_analyzed DATE,
		suspended INT,
		PRIMARY KEY (image_uri)
	);
	
CREATE TABLE color_freq(
--		id INT generated by default as identity (start with 1) not null,
		image_uri VARCHAR(2000) NOT NULL CONSTRAINT COLOR_FK  REFERENCES image ON DELETE CASCADE,
		color INT NOT NULL,
		relative_freq INT NOT NULL,
		PRIMARY KEY (image_uri, color)
	);