CREATE TABLE image(
--		id INT generated by default as identity (start with 1) not null,
		image_uri VARCHAR(2000) NOT NULL,
		date_analyzed DATE,
		suspended INT,
		PRIMARY KEY (image_uri)
	);
	
CREATE TABLE IMAGE_PAGE(
		image_uri VARCHAR(2000) NOT NULL CONSTRAINT IMAGE_PAGE_FK  REFERENCES image ON DELETE CASCADE,
		page_uri VARCHAR(2000) NOT NULL,
		PRIMARY KEY (image_uri, page_uri)
	);